namespace ALGON.LeetCodeProblems.BitManipulation
{
    /*Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.*/
    //23, 2 = 10, 3 = 11
    //0 ^ 10 = 10
    //10 ^ 11 = 01
    //01 ^ 10 = 11
    //11 ^ 11 = 0
    public class Solution_389
    {
        public char FindTheDifference(string s, string t)
        {
            int buff = 0;

            for (int i = 0; i < s.Length; i++)
            {
                buff ^= s[i];
            }

            for (int i = 0; i < t.Length; i++)
            {
                buff ^= t[i];
            }

            return (char)buff;
        }
    }
}
